### ISSUE TITLE
Command "decorator" AndThen is documented as being java-only, but it exists in C++ too

### ISSUE THREAD

**Issue by maximumsomething** [wpilibsuite/frc-docs#556] opened 2020-02-16 23:31 UTC
https://docs.wpilib.org/en/latest/docs/software/commandbased/convenience-features.html#andthen-java-only . Also, I question why AlongWith, RaceWith, and DeadlineWith are Java-only. Couldn't the other commands be passed in an initializer list?

**Comment by Oblarg** [comment] 2020-02-17 02:26
I'm too tired tonight to explain this in full detail, but the only `andThen` that exists in the C++ is non-polymorphic (it is guaranteed to be an `InstantCommand`).  Value-type polymorphism is impossible; it would be exceedingly difficult to implement this without an additional layer of CRTP hackery.

**Comment by maximumsomething** [comment] 2020-02-17 03:12
Interesting. I didn't see before that `AndThen` takes a `std::function`, not a command. 

May I ask why it can't call `TransferOwnership()` on commands that are passed as parameters? From what I can see, none of the command group classes store value types; they all use `unique_ptr`s. Also, (and I realize it's too late to change this, but...) Why not just use `shared_ptr` for commands everywhere?

I think it would be helpful if the documentation explains some of the template hackery that goes on. E.g. why we need `CommandHelper`.

(If you're too tired you don't have to answer tonight, lol)

**Comment by Oblarg** [comment] 2020-02-17 20:00
Using `shared_ptr` would have been a reasonable way to simply implement things the way there were in the java, but the `unique_ptr` is a better representation of the intended code structure as single command instances should not be reused from multiple places.

TransferOwnership is rvalue-qualified, and so can only be called on rvalues; thus, we'd have to template the decorators on the command types passed in (more or less duplicating the code that's currently in each of the command group ctors).  This isn't really worth doing; those particular decorators save a lot more verbosity in the Java than in the C++, to begin with.

Explaining the template stuff would probably be well-beyond the scope of what we can expect most high-schoolers to understand, unfortunately.

**Comment by maximumsomething** [comment] 2020-02-18 20:25
> Explaining the template stuff would probably be well-beyond the scope of what we can expect most high-schoolers to understand, unfortunately.

I disagree. Several students on my team know c++ deeply enough to understand a discussion about templates and move c-tors, and I think it's essential to understand this ownership-related trickery in order to use the command framework and know its limitations. (An example of one such limitation that's unobvious: the full type of a command must be known at compile time in order to add it to a command group correctly).

**Comment by Oblarg** [comment] 2020-02-18 20:27
I'll consider writing a frc-docs page on the C++ command ownership model, then.

**Comment by Starlight220** [comment] 2020-04-13 20:20
> the full type of a command must be known at compile time in order to add it to a command group correctly

This applies only to C++, correct?
About Java, there is an ongoing issue about something similar to this: https://github.com/wpilibsuite/allwpilib/pull/2451#issuecomment-612659834
About the issue itself, the docs should say that the correct way to run a lambda constantly is with a `RunCommand`, and not `InstantCommand.perpetually`.

**Comment by Daltz333** [comment] 2020-08-27 04:17
Closing as a duplicate of #573, we should document the internals of the C++ command-based

**Closed by Daltz333** 2020-08-27 04:17 UTC
