### ISSUE TITLE
"Internal issue with print and error tags" WPILIB 2024

### ISSUE THREAD

**Issue by nane4mv** [wpilibsuite/frc-docs#2543] opened 2024-01-18 19:26 UTC
Hi!! My team is having problems with WPILIB2024. When we deploy our code, it shows this message:  **_"Internal issue with print and error tags"_** . When we enable our code it works but after a while it desable itself. 

Does someone knows why this is happening?

**Comment by Starlight220** [comment] 2024-01-19 06:29
Duplicate of wpilibsuite/allwpilib#6174. Join the discussion there.

**Closed** 2024-01-19 06:29 UTC
