### ISSUE TITLE
Instructions for continuous integration

### ISSUE THREAD

**Issue by Modelmat** [wpilibsuite/frc-docs#524] opened 2020-01-29 03:03 UTC
There should be a page detailing how to set up continuous integration on the robot project. There is the roborio/WPILib docker image.

This probably should be vendor-agnostic although example configurations for azure/ other vendors would likely not hurt.

**Comment by ThadHouse** [comment] 2020-01-29 03:31
Closing because of duplicate of #57 

Definitely something we want. Would likely choose azure because it's cross platform, free, and really easy to use.

**Closed by ThadHouse** 2020-01-29 03:31 UTC

**Comment by Modelmat** [comment] 2020-01-29 03:33
Oops, the one time I forget to search :P.
