### ISSUE TITLE
Joystick article

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#822] opened 2020-09-12 18:59 UTC
There currently isn't an article about using joysticks. There are discussions in the command-based code and in getting started, but no general reference.

This article on screensteps would be a good place to start https://web.archive.org/web/20190119063303/http://wpilib.screenstepslive.com/s/currentCS/m/java/l/599723-joysticks
Other items to add beyond what's on screensteps:
POV
XBoxController
*Pressed methods

**Comment by Daltz333** [comment] 2020-09-12 19:02
It does actually exist in https://docs.wpilib.org/en/latest/docs/getting-started/running-a-benchtop/creating-benchtop-test-program-cpp-java.html and will likely be addressed in #796

**Comment by Daltz333** [comment] 2020-09-12 19:13
Actually, we'd need an article that goes over finding a joysticks axes (when not using Xbox controller), and the different parts as the OP says.

**Comment by Starlight220** [comment] 2020-09-12 19:31
The ScreenSteps article linked above is outdated, lacks some information, and generally isn't structured very well.
I suggest that the article about this would be structured as follows:
- General Overview
- `GenericHID` subclasses object initialization
- Reading Buttons
  - `XBoxController` constants
- Reading Axes
- Reading POV
- (maybe a link to the command-based `JoystickButton`/`Trigger` doc)?

**Comment by Daltz333** [comment] 2020-09-13 19:09
I am going to mark this as needing a design decision as I have to get a bit of thought on where this needs to go. However, work can still be done on the article itself.

**Comment by jasondaming** [comment] 2021-01-24 15:31
What I think I would suggest in the current structure is that we add a 5th step in Zero to Robot.  We make it very clear that this is optional but highly recommended.  In this step we detail out the basic things that nearly all teams need to do in the first say 5 hours of programming / getting their bot running.  We would also try to explain a little more of the "why", I know some of these things are subjective and teams disagree on what is best however I won't to focus on the simple things that almost every team would agree is in a "rookies" best interest.  Now I think most of these things rather than be a complete comprehensive guide (as that would be way too long and complicated) will just introduce them to the concept and then link them to the more detailed documentation elsewhere.  Things I can think of that fall into this introduce and link paradigm would be like: simple motor control, pneumatics, simple auto, drive control optimization, and maybe even basic PID.

I did say most as I don't think this is true for Joysticks.  Every single team needs a decent understanding of Joysticks their axis and buttons.

**Comment by Daltz333** [comment] 2021-01-24 16:52
Yep, I agree on that! My goal is that the 5th step include optional drivetrain tutorials.

**Comment by jasondaming** [comment] 2021-01-24 19:46
Is this something (the 5th step) that we can add now?  I know we aren't doing structural changes now but does adding things like this count?

**Comment by Daltz333** [comment] 2021-04-03 03:38
Duplicate of #303

**Closed by Daltz333** 2021-04-03 03:38 UTC
Labels: Needs Design Decision, Type: New Article

**Comment by sciencewhiz** [comment] 2021-04-03 17:10
While there is some overlap with #303, it isn't really a duplicate. #303 is asking for more advanced usage of the HID class, this is more basic.

**Comment by Daltz333** [comment] 2021-04-03 17:24
@jasondaming and I conversation noted that is very plausible to just combine the two usages into one article.

**Comment by sciencewhiz** [comment] 2021-04-03 17:29
That is true, that one article might close both issues, but it would also be possible to create an article that resolves #303, but doesn't resolve this issue.

**Comment by Daltz333** [comment] 2021-04-03 18:05
@jasondaming I think the scope of #303 should include this, as such this is closed.
