### ISSUE TITLE
New Article on LabView Dashboard

### ISSUE THREAD

**Issue by yellowjaguar5** [wpilibsuite/frc-docs#658] opened 2020-05-08 00:32 UTC
Per the `todo` note on this section of the [Control System Software Overview](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/getting-started/getting-started-frc-control-system/control-system-software.rst#frc-labview-dashboard-windows-only) article, an article needed to be ported regarding the default LabView Dashboard, but I have not been able to find an article about it in Screensteps (or the archive.org version of Screensteps). Should one be written?

**Comment by Daltz333** [comment] 2020-05-08 00:59
Duplicate of #340

**Closed by Daltz333** 2020-05-08 00:59 UTC
