### ISSUE TITLE
Building and deploying should have a troubleshooting section

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#392] opened 2019-12-25 16:01 UTC
List common problems and what the output looks like:
wrong image
No network connection
code crashing

**Comment by JonathanLindsey** [comment] 2020-09-20 20:17
I believe this is a duplicate of #515 and there is more discussion over there.

**Comment by Daltz333** [comment] 2020-09-20 20:22
Closing in favor of #515

**Closed by Daltz333** 2020-09-20 20:22 UTC
Labels: Type: New Article
