### ISSUE TITLE
Document geometry classes

### ISSUE THREAD

**Issue by ItayZiv** [wpilibsuite/frc-docs#709] opened 2020-06-11 19:29 UTC
Its probably worth having at least 1 article covering the basic Translation2d, Rotation2d, Pose2d (and the reasoning behind them, and maybe a bit about how to work with them) and more importantly Twist2d (what it is and how to use it).

**Comment by Daltz333** [comment] 2020-06-11 19:30
Possible duplicate of #698

**Comment by ItayZiv** [comment] 2020-06-11 22:34
The 2 issues could be merged, but I'm talking about more general documentation of the basic classes and why they exist (units stuff for rotation, etc) and about what Twist2d is, what #698 is referencing would probably go under the same article/s

**Closed** 2020-07-02 17:26 UTC
Labels: Type: New Article
