### ISSUE TITLE
Documenting/Tutorial of Sim is needed

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#704] opened 2020-06-08 07:37 UTC
This will include also #374 :

The following things need to be documented. A tutorial including all of these should also be created.
- [x]  Using the SimDevice API - purpose, usage, perhaps defining custom SimDevice types
- [x]  Unit Testing in sim - perhaps some docs about unit testing in general too
- [x]  Sim GUI - purpose, usage, full capabilities, trajectory manipulation/view
- [x] What can realistically be done in sim (testing logic, etc), and what has to be run on the physical robot (tuning constants, etc)
- [ ] Those modules @Kython89 mentioned [here](https://github.com/wpilibsuite/frc-docs/issues/374#issuecomment-573986610) - `lowfi_simulation`, `halsimprint`, `halsim_ds_nt`, `halsim_ds_socket`
- [x] Running NT, etc in Local mode for tests (perhaps this should be somewhere else)
- [x] JUnit, etc?

**Comment by Daltz333** [comment] 2020-06-08 14:18
Partly duplicate of #374

**Comment by Starlight220** [comment] 2020-06-08 15:29
Then I'll include #374 in this, so that can perhaps be closed.

**Comment by Starlight220** [comment] 2020-08-27 16:34
I think this partially depends on the state-space integration, though I will try to build a PR with what is currently in WPILib.

**Comment by mcm001** [comment] 2020-11-22 18:55
This comment's a bit late, but state-space has been merged and there's a relatively small example included. there's example projects for everything else

**Comment by Starlight220** [comment] 2020-11-22 19:44
Yeah, I forgot about this issue. I was able to get a simulation and unit test running a while back, and I wrote Javadocs for most of the simulation classes, I will try to write something for this.

**Comment by Starlight220** [comment] 2021-01-04 20:35
How in-depth should this be? 
I recently posted info about the SimDevice API on [Chief Delphi](https://www.chiefdelphi.com/t/robot-simulator-not-working/389367/7?u=starlight220). 

An updated list of topics, I'm not sure that all of them should be in frc-docs:
- [ ] State Space
- [ ] `RobotBase.isReal()` to check for real or simulation
- [ ] `SimDeviceSim`/`SimValue`
- [ ] `SimDevice` (and the difference from `SimDeviceSim` - though the difference *should* be in the API docs)
- [ ] the `register<Property>Callback` functions in the `XxxSim` classes (assuming that those classes *are* included with the `get`/`set` functions)
- [ ] `stepTiming()` etc

I would be happy to get some design insight about this.

**Comment by Daltz333** [comment] 2021-01-04 20:41
Unit Testing with Glass and Simulation

**Comment by Starlight220** [comment] 2021-01-04 20:46
What about it?

**Comment by Starlight220** [comment] 2021-01-09 17:19
I'm adding this as a section in `Advanced Programming`, or do you want this somewhere else?

**Comment by Daltz333** [comment] 2021-01-09 17:24
I think it should stay in robot simulation, as that is it's intended purpose.

**Closed** 2021-03-19 03:09 UTC
Labels: Help Wanted, Type: New Article
